[package]
name = "extension-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
bitflags = "1.3.2"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
wasmtime = "0.34.0"
wasmtime-wasi = { version = "0.34.0", features = ["tokio"]}
wasi-common = "0.34.0"
env_logger = "0.9.0"
cap-std = "0.22.0"
thiserror = "1.0.30"
futures-util = "0.3.19"
async-trait = "0.1.52"
semver = { version = "1.0.4", features = ["serde"] }
cached = "0.26.2"
tracing = "0.1.29"
common = { path = "../common" }

[dev-dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tracing-subscriber = "0.2"