[package]
name = "extension-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
bitflags = "1.3.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
wasmtime = "0.34.1"
wasmtime-wasi = { version = "0.34.1", features = ["tokio"] }
wasi-common = "0.34.1"
env_logger = "0.9.0"
cap-std = "0.24.1"
thiserror = "1.0.30"
futures-util = "0.3.21"
async-trait = "0.1.52"
semver = { version = "1.0.6", features = ["serde"] }
cached = "0.30.0"
tracing = "0.1.31"
common = { path = "../common" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
tracing-subscriber = "0.3.9"
