[package]
edition = "2021"
name = "wasi-mtt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# These dependencies are necessary for the witx-generation macros to work:
anyhow = "1.0.58"
futures-util = "0.3.21"
tauri = "1.0.4"
thiserror = "1.0.31"
tokio = "1.20.0"
tracing = "0.1.35"
wasmtime = "0.38.3"
wiggle = "0.38.1"
workspace-hack = {version = "0.1", path = "../workspace-hack"}

[build-dependencies]
walkdir = "2.3.2"

[badges]
maintenance = {status = "experimental"}
