[workspace]
members = ["desktop/app", "desktop/wasi-mtt", "desktop/workspace-hack"]

# default to small, optimized workspace release binaries
[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
panic = "abort"
