name: CI setup

description: |
  Sets up the CI environment for the project

inputs:
  matrix-os:
    description: 'The Current OS'
    required: true
  # matrix-target:
  #   description: "The Current Target"
  #   required: true
  # matrix-goarch:
  #   description: "The Current Go Arch"
  #   required: true

runs:
  using: 'composite'

  steps:
    - name: 'Setup Go'
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: 'Install native packages'
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf
      shell: bash

    - name: Setup cache Ubuntu
      uses: actions/cache@v3
      if: inputs.matrix-os == 'ubuntu-latest'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup cache Macos
      uses: actions/cache@v3
      if: inputs.matrix-os == 'macos-latest'
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup cache Windows
      uses: actions/cache@v3
      if: inputs.matrix-os == 'windows-latest'
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Import MacOS certs
      if: inputs.matrix-os == 'macos-latest'
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

    - name: Install Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'yarn'

    - name: Install Frontend Dependencies
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
      run: |
        yarn set version latest
        yarn
      shell: bash
