[package]
name = "mintter"
version = "0.1.0"
description = "A publishing platform where other content creators can reuse your content keeping your authorship and royalties."
authors = ["The mintter team"]
license = ""
repository = ""
default-run = "mintter"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.3", features = [] }

[dependencies]
tauri = { version = "1.0.0-rc.3", features = ["cli", "shell-execute", "shell-open", "system-tray"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/tauri-plugin-log", branch = "dev", features = ["colored"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store", branch = "refactor/builder-pattern" }
tokio = { version = "1.17.0", features = ["full"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
log = "0.4.14"
cap-std = "0.24.1"
anyhow = "1.0.55"
env_logger = "0.9.0"
extension-host = { path = "../extension-host" }
common = { path = "../common" }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
