[package]
name = "mintter"
version = "0.0.0" # don't touch! This gets overriden with the correct version by CI.
description = "A publishing platform where other content creators can reuse your content keeping your authorship and royalties."
authors = ["The mintter team"]
license = ""
repository = ""
default-run = "mintter"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
tauri = { version = "1.0.0", features = ["cli", "shell-execute", "shell-open", "system-tray", "window-maximize", "window-start-dragging", "window-unmaximize"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/tauri-plugin-log", rev = "0e993f8ded5867772b29ca7aee5bc5594aba6fb9", features = ["colored"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store", rev = "5726952177b88d1d10063cdf8e7506bac84772cf" }
tokio = { version = "1.19.2", features = ["full"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
log = "0.4.17"
anyhow = "1.0.57"
env_logger = "0.9.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
url = "2.2.2"
thiserror = "1.0.31"
# cap-std = "0.24.3"
# extension-host = { path = "../extension-host" }
# common = { path = "../common" }

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24.0"
objc = "0.2.7"

[target."cfg(target_os = \"linux\")".dependencies]
webkit2gtk = "0.18.0"

[target."cfg(target_os = \"windows\")".dependencies]
windows = "0.37.0"
webview2-com = "0.17.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
