name: Audit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # audit-javascript:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: "Setup NodeJS"
  #       uses: actions/setup-node@v3
  #       with:
  #         cache: yarn
  #         node-version: 16.x
  #     - name: audit
  #       run: yarn audit
