name: Site docker

on:
  push:
    branches:
      - 'build13/staging'
      
jobs:
  generate-docker-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push mintterd
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/cmd/mintterd/Dockerfile
          tags: mintter/mintterd:latest
      -
        name: Build and push nextjs
        uses: docker/build-push-action@v4
        with:
          push: true
          file: frontend/gateway/Dockerfile
          tags: mintter/sitegw:latest