name: Update Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '50 6 * * 0-6'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1

jobs:
  generate-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push mintter-site
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/cmd/mintter-site/Dockerfile
          tags: mintter/mintter-site:latest
      - name: Build and push mintterd
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/cmd/mintterd/Dockerfile
          tags: mintter/mintterd:latest
      - name: Build and push nextjs
        uses: docker/build-push-action@v4
        with:
          push: true
          file: frontend/apps/site/Dockerfile
          tags: mintter/sitegw:latest
      - name: Build and push monitord
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/cmd/monitord/Dockerfile
          tags: mintter/monitord:latest
      - name: Build and push gateway
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/cmd/minttergw/Dockerfile
          tags: mintter/minttergw:latest
      - name: Build and push relay
        uses: docker/build-push-action@v4
        with:
          push: true
          file: backend/cmd/relayd/Dockerfile
          tags: mintter/relayd:latest
