name: Lint

on:
  push:
  pull_request:

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Install clippy with stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Mock Files
        run: |
          mkdir -p plz-out/bin/backend
          touch plz-out/bin/backend/mintterd-x86_64-unknown-linux-gnu
          mkdir -p plz-out/gen/frontend/dist/client
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
          name: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=Cargo.toml --all -- --check

  lint-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - run: yarn lint

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          only-new-issues: true
          args: --timeout=5m
