name: Lint JavaScript

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/lint-desktop.yml'
      - 'frontend/apps/desktop/**'
  pull_request:
    paths:
      - '.github/workflows/lint-desktop.yml'
      - 'frontend/apps/desktop/**'
    branches-ignore:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      
      - name: Install Dependencies
        run: |
          yarn set version latest
          yarn install --immutable --immutable-cache --check-cache
      
      - name: Validate Files
        run: yarn desktop:validate

  # lint-go:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: latest
  #         only-new-issues: true
  #         args: --timeout=5m
