name: Create Release Candidate

on:
  push:
    branches:
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get_latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          # excludes: rc, alpha, beta # Optional. Exclude keywords like rc, alpha, beta releases.

      - name: Bump release candidate version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.get_latest_release.outputs.release }}
          version-fragment: "rc"

      - name: LOG Release Candidate
        run: |
          echo "RELEASE: ${{ steps.bump_version.outputs.next-version }}"
