name: Release

on:
  push:
    tags:
      - desktop/*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    needs: create-release
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            daemon_path: plz-out/bin/backend/mintterd-x86_64-unknown-linux-gnu
            goarch: amd64
          - os: macos-latest
            daemon_path: plz-out/bin/backend/mintterd-x86_64-apple-darwin
            goarch: amd64
          - os: macos-latest
            daemon_path: plz-out/bin/backend/mintterd-aarch64-apple-darwin
            goarch: arm64
          - os: windows-latest
            daemon_path: plz-out/bin/backend/mintterd-x86_64-pc-windows-msvc.exe
            goarch: amd64
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Rust"
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: "Setup NodeJS"
        uses: actions/setup-node@v1
        with:
          cache: yarn
          node-version: 16.x
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: "Install required packages"
        if: "matrix.os == 'ubuntu-latest'"
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: "Install app dependencies"
        run: yarn
      - name: Build Backend
        run: |
          mkdir -p plz-out/bin/backend
          go build -o ${{ matrix.daemon_path }} ./backend/cmd/mintterd
        env:
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
      - uses: tauri-apps/tauri-action@v0
        env:
          APPLE_CERTIFICATE: "${{ secrets.APPLE_CERTIFICATE }}"
          APPLE_CERTIFICATE_PASSWORD: "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}"
          APPLE_ID: "${{ secrets.APPLE_ID }}"
          APPLE_PASSWORD: "${{ secrets.APPLE_PASSWORD }}"
          APPLE_SIGNING_IDENTITY: "${{ secrets.APPLE_SIGNING_IDENTITY }}"
          ENABLE_CODE_SIGNING: "${{ secrets.APPLE_CERTIFICATE }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          configPath: release.tauri.conf.json
          includeDebug: true
          projectPath: ./desktop/app
          releaseId: "${{ steps.create_release.outputs.id }}"

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: create_release
        name: "create release"
        uses: softprops/action-gh-release@master
        with:
          body: ""
          draft: true

  publish:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: create_release
        name: "create release"
        uses: softprops/action-gh-release@master
        with:
          draft: false
