name: Test Go

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test-go.yml"
      - "go.mod"
      - "backend/**"
  pull_request:
    paths:
      - ".github/workflows/test-go.yml"
      - "go.mod"
      - "backend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test ./backend/...
