name: Unit Test JavaScript

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-javascript.yml'
      - 'frontend/**'
      - 'package.json'
  pull_request:
    paths:
      - '.github/workflows/test-javascript.yml'
      - 'frontend/**'
      - 'package.json'
    branches-ignore:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run UI tests
        run: pnpm test:ui
