name: Rust Udeps

on:
  push:
  pull_request:

jobs:
  udeps:
    runs-on: ubuntu-latest
    container: iterpre/tauri
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Mock Files
        run: |
          mkdir -p plz-out/bin/backend
          touch plz-out/bin/backend/mintterd-x86_64-unknown-linux-gnu
          mkdir -p plz-out/gen/frontend/dist/client
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked
      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --workspace --manifest-path=Cargo.toml --all-targets --all-features
