name: Validate + Test Desktop code

on:
  push:
    branches:
      - master
      - electron-ci
    paths:
      - '.github/workflows/validate-desktop.yml'
      - 'frontend/apps/electron/**'
      - 'frotend/packages/**'
      - 'package.json'
      - 'frontend/apps/electron/package.json'
  pull_request:
    paths:
      - '.github/workflows/validate-desktop.yml'
      - 'frontend/apps/electron/**'
      - 'frotend/packages/**'
      - 'package.json'
      - 'frontend/apps/electron/package.json'
    branches-ignore:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-test-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup
        with:
          matrix-os: 'ubuntu-latest'

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Frontend Dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          yarn

      - name: Validate code
        run: |
          yarn desktop:validate
          yarn desktop:lint

      - name: Package desktop app
        run: |
          yarn build
          yarn desktop:package

      - name: Run desktop app tests
        run: yarn desktop:test
