[package]
name = "ext-youtube"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
serde_json = "1.0.79"
common = { path = "../common" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
